version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres-d
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mytestdb
    volumes:
      - ./data:/var/lib/postgresql/data
#  redis:
#    image: redis
#    container_name: redis-d
#    restart: on-failure